---
galaxy_info:
  author: Markus Brechtel
  description: Deploy-deploy deploys all the deployment things required to deploy ALL THE THINGS!
  license: Apache-2.0
  min_ansible_version: '2.14'
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - deployment
    - systemd
    - automation

dependencies: []