---
galaxy_info:
  author: Markus Katharina Brechtel
  description: Test role for basic deployment validation
  license: Apache-2.0
  min_ansible_version: '2.14'
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - testing

dependencies: []