---

- name: Deploy the RPS Deployment System for the current user account
  hosts: localhost
  become: true
  roles:
    - deploy_deploy
    - test_instance
    - role: ansible_play
      deploy_instance_id: ohai
      ansible_play_git_repo: "{{playbook_dir}}"
      ansible_play_import_playbook_filename: ohai.yaml
