---
galaxy_info:
  author: Markus Katharina Brechtel
  description: Git-based pull deployment strategy
  license: Apache-2.0
  min_ansible_version: '2.14'
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - deployment

dependencies: []