---
galaxy_info:
  author: Markus Katharina Brechtel
  description: HTTP webhook trigger support for deployments
  license: Apache-2.0
  min_ansible_version: '2.14'
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - deployment
    - webhook

dependencies: []